services:
  web:
    build:
      context: .
      dockerfile: web.dockerfile
    restart: always
    ports:
      - "80:80"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  queue:
    build:
      context: .
      dockerfile: worker.dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: 
      - php
      - artisan
      - queue:work

  scheduler:
    build:
      context: .
      dockerfile: worker.dockerfile
    restart: always
    env_file:
      - .env
    depends_on:
      - db
      - redis
    command: 
      - php
      - artisan
      - schedule:work

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always

volumes:
  pg_data:
